// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_21 = "CgkIiYjO67ULEAIQFw"; // <GPGSID>
        public const string achievement_15 = "CgkIiYjO67ULEAIQEQ"; // <GPGSID>
        public const string achievement_11 = "CgkIiYjO67ULEAIQCw"; // <GPGSID>
        public const string achievement_22 = "CgkIiYjO67ULEAIQGQ"; // <GPGSID>
        public const string achievement_13 = "CgkIiYjO67ULEAIQDQ"; // <GPGSID>
        public const string achievement_17 = "CgkIiYjO67ULEAIQEw"; // <GPGSID>
        public const string achievement_25 = "CgkIiYjO67ULEAIQHg"; // <GPGSID>
        public const string achievement_18 = "CgkIiYjO67ULEAIQFA"; // <GPGSID>
        public const string achievement_12 = "CgkIiYjO67ULEAIQDA"; // <GPGSID>
        public const string achievement_9 = "CgkIiYjO67ULEAIQEA"; // <GPGSID>
        public const string achievement_2 = "CgkIiYjO67ULEAIQCA"; // <GPGSID>
        public const string achievement_3 = "CgkIiYjO67ULEAIQDw"; // <GPGSID>
        public const string achievement = "CgkIiYjO67ULEAIQAw"; // <GPGSID>
        public const string achievement_6 = "CgkIiYjO67ULEAIQGA"; // <GPGSID>
        public const string achievement_7 = "CgkIiYjO67ULEAIQHQ"; // <GPGSID>
        public const string achievement_4 = "CgkIiYjO67ULEAIQGg"; // <GPGSID>
        public const string achievement_5 = "CgkIiYjO67ULEAIQCQ"; // <GPGSID>
        public const string achievement_20 = "CgkIiYjO67ULEAIQFg"; // <GPGSID>
        public const string achievement_8 = "CgkIiYjO67ULEAIQCg"; // <GPGSID>
        public const string achievement_10 = "CgkIiYjO67ULEAIQBw"; // <GPGSID>
        public const string leaderboard_one = "CgkIiYjO67ULEAIQBg"; // <GPGSID>
        public const string achievement_23 = "CgkIiYjO67ULEAIQGw"; // <GPGSID>
        public const string achievement_24 = "CgkIiYjO67ULEAIQHA"; // <GPGSID>
        public const string achievement_16 = "CgkIiYjO67ULEAIQEg"; // <GPGSID>
        public const string achievement_14 = "CgkIiYjO67ULEAIQDg"; // <GPGSID>
        public const string achievement_19 = "CgkIiYjO67ULEAIQFQ"; // <GPGSID>

}

